### PR TITLE
Updated

### PR DESCRIPTION
**Pull request by alhamesrami**
If possible, to provide the context of the following terms:
Line 130: HVM
Line 136: Interface down
Line 141: Kernel
Line 238: Pro
Line 255: reiserfs

### CODE REVIEW

**Comment by spencerjunraid** [comment]
Hello @alhamesrami,
L255: reiserfs is a type of file system. Can be left as is.
L238: Pro is a license tier for Unraid. There is Basic, Plus and Pro https://unraid.net/pricing
L141- kernel is talking about the Linux kernel. Basically the version of the linux software.
@bergware - please verify above and comment on "Interface down" and "HVM" si vouz plait.

**Comment by bergware** [comment]
**HVM** is the abbreviation of Hardware Virtualization Machine, it tells if hardware supports VMs
**Interface down** is a status message telling the interface is disconnected (down)

**Comment by alhamesrami** [comment]
All set to go. The terms were corrected in the main. 
**Yestime** (Lines 366-368) is the NY company https://yestime.com/ right?

**Comment by bergware** [comment]
Yes Time Machine=Yes (Time Machine)
YesTime Machine hidden=Yes/Time Machine (hidden)
YesTime Machine=Yes/Time Machine

**Comment by alhamesrami** [comment]
> Yes Time Machine=Yes (Time Machine)
> YesTime Machine hidden=Yes/Time Machine (hidden)
> YesTime Machine=Yes/Time Machine

OK, all done then.

**Comment by spencerjunraid** [comment]
great- thanks!

**Comment by alhamesrami** [comment]
comments added to #23, please change the 3 lines and the file is done

**Pull request merged**
